export default [
  "Aardvark",
  "Abecedarians",
  "Aborigine",
  "Addle-pated lumps of anthracite",
  "Alcoholic",
  "Anachronisms",
  "Anacoluthons",
  "Antediluvian bulldozer",
  "Anthracite",
  "Anthropithecus",
  "Anthropophagus",
  "Arabian Nightmare",
  "Artichokes",
  "Autocrats",
  "Aztecs",
  "Baboon",
  "Baby-snatchers",
  "Bagpipers",
  "Bald-headed budgerigar",
  "Balkan Beetle",
  "Bandit",
  "Bandicoots",
  "Bashi-bazouks",
  "Bath-tub Admiral",
  "Beast",
  "Belemnite",
  "Big-head",
  "Billions of blue blistering boiled and barbecued barnacles",
  "Billions of bilious barbecued blue blistering barnacles",
  "Billions of bilious blue blistering barnacles",
  "Billions of bilious blue blistering barnacles in a thundering typhoon",
  "Billions of blue blistering barnacles",
  "Black-beetles",
  "Black marketeers",
  "Blackamoor",
  "Blackbird",
  "Blackguards",
  "Blistering Barnacles",
  "Blistering blundering birdbrain",
  "Blistering Eardrums",
  "Bloodsuckers",
  "Blue blistering barnacles",
  "Blue Blistering Bell-Bottomed Balderdash",
  "Blunderbuss",
  "Body-snatcher",
  "Bootlegger",
  "Borgia",
  "Bougainvillea",
  "Brat",
  "Breathalyser",
  "Brigand",
  "Brutes",
  "Buccaneer",
  "Bully",
  "Butcher",
  "Cachinnating cockatoo",
  "Cannibal",
  "Carpet-sellers",
  "Caterpillars",
  "Centipede",
  "Cercopithecus",
  "Certified diplodocuses (a pun on the Bordurian embassy car's CD plate)",
  "Coconuts",
  "Coelacanth",
  "Colocynths",
  "Corsair",
  "Cowards",
  "Crabapples",
  "Cro-Magnon",
  "Crooks",
  "Clumsy-footed quadrupeds",
  "Cushion footed quadrupeds",
  "Cyclone",
  "Cyclotron",
  "Dictatorial duck-billed diplodocus",
  "Diplodocus",
  "Dipsomaniac",
  "Dizzard",
  "Dogs",
  "Doryphore (Used as a racist term in French for a German person",
  "Duck-billed platypus",
  "Dunderheaded coconuts",
  "Dunderheaded Ethelreds",
  "Dynamiter",
  "Dinosaurs",
  "Ectoplasmic byproduct",
  "Ectoplasm",
  "Egoists",
  "Fancy-dress Fascist",
  "Fancy-dress Fatima",
  "Fancy-dress freebooter",
  "Fatfaces",
  "Filibuster",
  "Flaming Jack-in-the-Box",
  "Fourlegged Cyrano",
  "Freshwater pirate",
  "Freshwater swabs",
  "Fuzzy-wuzzy",
  "Freshwater politicians",
  "Freshwater Spacemen",
  "Gallows-fodder",
  "Gang of thieves",
  "Gangsters",
  "Gibbering anthropoids",
  "Gibbering ghost",
  "Great flat-footed grizzly bear",
  "Gobbledygooks",
  "Gogglers",
  "Goosecaps",
  "Guano gatherer",
  "Gyroscope",
  "Harlequin",
  "Heretic",
  "Highwayman",
  "Hi-jackers",
  "Hoodlum",
  "Hooligans",
  "Hydrocarbon",
  "Iconoclast",
  "Idiots",
  "Interplanetary goat",
  "Interplanetary Pirates",
  "Invertebrate",
  "Jellied eel",
  "Jellyfish",
  "Jobbernowl TT60",
  "Kleptomaniacs",
  "Ku Klux Klan",
  "Licorice-livered lubberly scum in thousands of thundering typhoons",
  "Liquorice",
  "Lily-livered landlubbers",
  "Lily-livered bandicoots",
  "Loathsome brute",
  "Logarithm",
  "Lubberly scum",
  "Macrocephalic baboon",
  "Meddlesome Cabin Boy",
  "Megacycle TT60",
  "Megalomaniac",
  "Mameluke",
  "Miserable bird",
  "Miserable blundering barbecued blister",
  "Miserable earthworms",
  "Miserable miser",
  "Miserable molecule of mildew",
  "Misguided missles",
  "Mister Mule",
  "Monopolizers",
  "Monster",
  "Morons",
  "Moujiks",
  "Mountebanks",
  "MRKRPXZKRMTFRZ",
  "Musical morons",
  "Murderers",
  "Millions and billions of blue blistering barnacles",
  "Nanny Goat",
  "Nest of rattlesnakes",
  "Nincompoop",
  "Nitwits",
  "Nitwitted ninepins",
  "Numbskulls",
  "Nyctalops",
  "Odd-toed ungulate",
  "Olympic athlete",
  "Ophicleides",
  "Orangoutang",
  "Ostrogoth",
  "Pachyrhizus",
  "Paranoiac",
  "Parasites",
  "Patagonians",
  "Pestilential pachyderm",
  "Phylloxera",
  "Picaroons (from Spanish: pícaro",
  "Pickled herrings",
  "Pirates",
  "Pithecanthropic",
  "mountebanks",
  "Pithecanthropic pickpocket",
  "Pithecanthropic pockmark",
  "Pithecanthropuses",
  "Pockmarks",
  "Politician",
  "Poltroons",
  "Polygraphs",
  "Polynesian",
  "Prattling",
  "porpoise",
  "Profiteers",
  "Psychopath",
  "Purple profiteering jellyfish",
  "Pyrographers",
  "Pyromaniac",
  "Raggle taggle ruminants",
  "Rapscallion",
  "Rats",
  "Rhizopods",
  "Road roller",
  "Road hogs",
  "Ruffian",
  "RKRPXZKRMTFRZ",
  "Rotten sand-hoppers",
  "Saucy tramp",
  "Savages",
  "Scoffing braggart",
  "Scorpion",
  "Sea gherkin",
  "Sea-lice",
  "Sea lion",
  "Shipwreckers",
  "Slave trader",
  "Slubberdegullions",
  "Sparrows",
  "Spitfire",
  "Squawking popinjay",
  "Steamrollers",
  "Stoolpigeon",
  "Subtropical sea-louse",
  "Swine",
  "Sycophant",
  "Technocrat",
  "Ten thousand thundering typhoons",
  "Terrapins",
  "Terrorists",
  "Thundering nitwitted numbskull you",
  "Thundering nitwitted seagherkin",
  "Thundering typhoons",
  "Tin hatted tyrants",
  "Toads",
  "Toffee-noses",
  "Torturers",
  "Traitors",
  "Tramps",
  "Tribe of Polynesians",
  "Troglodyte",
  "Turncoats",
  "Twister",
  "Two-timing Tartar twister",
  "Two-timing Troglodytes",
  "Vagabonds",
  "Vampires",
  "Vandal",
  "Vegetarian",
  "Vermicellis",
  "Villain",
  "Viper",
  "Visigoths",
  "Vulture",
  "Weevils",
  "Whippersnapper",
  "Wildcat",
  "Woodlice",
  "Wreckers",
  "Young monkey",
  "Zapotecs"
]