export default [
  "Anfäkta och anamma",
  "Anamma och regera alla världens andemakter",
  "Amiral Nelsons alla bomber och granater och kanoner",
  "Amöbor",
  "Apsvansade analfabeter",
  "Apspektakel",
  "Asgamar",
  "Avskyvärt",
  "Babian",
  "Bandit",
  "Banditskojaren",
  "Bestar",
  "Bladlus",
  "Blindstyren",
  "Blixt",
  "Blodsugare",
  "Blåkullatomtar",
  "Blötdjur",
  "Bomber och granater och krevader",
  "Bondlurkar",
  "Bovar",
  "Bålnötter",
  "Bödel",
  "Deghögar",
  "Det var som topp tusen tunnor",
  "Drummel",
  "Drönare",
  "Dunder och brak",
  "Du är en pesto...klyster",
  "Dyngspridare",
  "Dårhushjon",
  "Död och pina",
  "Eländiga kryp",
  "Enögda kannibal",
  "Erbarmliga plattfötter",
  "Far och flyg",
  "Fega ynkryggar",
  "Fåntrattar",
  "Fähund",
  "Fördömda kräk",
  "Förpiskade luspudlar",
  "För hundra gubbar",
  "För sjutton hakar",
  "Gamla knölsvan",
  "Gangster",
  "Gargantuaner",
  "Giftblåsan",
  "Gnom",
  "Gråsuggor och spindelapor",
  "Gravade oxsvansar",
  "Grobianer",
  "Groteskt",
  "Grottmänniskor",
  "Gråsuggor och dreglande paddor",
  "Gräsligt",
  "Gyckel",
  "Hamstrare",
  "Huggormars avföda",
  "Idiot",
  "Injsögangster",
  "I alla milda makters namn",
  "Jäklar",
  "Jäkla general",
  "Jäkla odjur",
  "Jämmer och elände",
  "Kanalier",
  "Kanapéer och konjakskransar",
  "Kannibal",
  "Karnevalsdiktatorn",
  "Kloakdjur",
  "Kloakråtta",
  "Klorlutsoppan",
  "Kramsfågelmördare",
  "Krevader och kanoner",
  "Kryddkrämare",
  "Krämare",
  "Legodrängar",
  "Lekstugefasoner",
  "Lumphandlare",
  "Luspudlar",
  "Luskungar",
  "Lymmel",
  "Lögnhalsar",
  "Lönnmördare",
  "Maskar",
  "Milda makter",
  "Murmeldjur",
  "Möshumlor",
  "Nu blommar asfalten",
  "Nu går skam på torra land",
  "Ockrare",
  "Oduglingar",
  "Orangutang",
  "Parasiter",
  "Pestråtta",
  "Pest och pina",
  "Pillerbagge",
  "Pirater",
  "Pistaschgubbar och surkålsstuvning",
  "Plattfötter",
  "Potatisgrisar",
  "Pottsorkar",
  "Pyromanapa",
  "Rena rävgiftet",
  "Rena sammansvärjningen",
  "Rena snurren",
  "Rena vansinnet",
  "Rotborstar",
  "Rullsvansapa",
  "Råttsvansar",
  "Rödskinnen",
  "Rötägg",
  "Sakramentskade sumprunkare",
  "Sabotörer och pestråttor",
  "Sladderfågel",
  "Sillmjölkar",
  "Skabbhalsar",
  "Skabbråttor",
  "Skamligt",
  "Skojare",
  "Skottkolvar",
  "Skurkar",
  "Skunkdjur",
  "Slavhandlare",
  "Slyn-yngel",
  "Snack och strunt och snack",
  "Snorvalp",
  "Snyltror på ädel tistelstam",
  "Sopprötter",
  "Sumpråtta",
  "Sötvattenspirater",
  "Tusan",
  "Tjockskalle",
  "Tjurskalle",
  "Tjuvar",
  "Tryffelsvin",
  "Tångräka",
  "Urfånigt",
  "Uslingar",
  "Vagabonder",
  "Vandaler",
  "Vegetarian",
  "Vidriga apmänniska",
  "Vidriga varulvar",
  "Vinlus",
  "Vrakplundrare",
  "Vrålapor",
  "Vårtsvin",
  "Åsneskallar",
  "Ärkebanditer",
  "Ärkeboven",
  "Ärkelögnare",
  "Anåda och anagga",
  "Avsigkomne",
  "Blixt och dunder och miljoner tyfoner",
  "Blixt och skatter",
  "Bläckfiskar",
  "Din olycka",
  "Din skråpuk",
  "Ditt bjäbbande spöke",
  "Ditt enödga murmeldjur",
  "Era tjattrande kariblar",
  "För bövelen",
  "Fördubblade babianer",
  "Fördubblade galenskaper",
  "För höge farao",
  "Gorillor",
  "Iglar och blodsugare",
  "Jag ska göra papegojpaj av hela rasket",
  "Knölfötter",
  "Kornblixtar och tyfoner",
  "Kors i världen",
  "Kreatur",
  "Lomhörda lymmel",
  "Maneter",
  "Markattor",
  "Monster och morsgrisar",
  "Passgångarna",
  "Pottsorkar och palsternackor",
  "Sjögurkor",
  "Småfjantar",
  "Stendöva stallknekt",
  "Stinkbomben",
  "Tokskallar",
  "Vedervärdige",
  "Vid alla nerlusade sopprötter",
  "Vid alla piskande råttsvansar"
]